#!/usr/bin/env bash
#Transfers a file from our client to a server

if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit
fi
file_path=$1
server=$2
username=$3
if [ $# -eq 4 ]
then
    private_key=$4
fi
scp -i "$private_key" "$file_path" "$username"@"$server":~/
