#!/usr/bin/env bash
#uses the trap command
# shellcheck disable=SC2050

command(){
    echo "I am invicible!!!"
}
while [ 5 -le 10 ]
do
    trap command TERM
    echo "To infinty and beyond"
    sleep 2
done
