#!/usr/bin/env bash
#This script is displaying "Best School" 10 times

for i in $(seq 1 10)
do
    if [$i -eq 10]
    then
        echo -n "Best School"
    else
        echo "Best School"
    fi
done
